### ISSUE TITLE
Design and deploy Database Schema

### ISSUE THREAD

**Issue by mikesimps** [open-force/website#8]
Setup database schema to support persistent storage and remove repo as source of data.

**Comment by ChuckJonas** [comment]
I'm sure I'm just out of the loop but why was it decided that we need a database?  Seems like a lot of extra added complexity for very little return at this point.  Setup, Development, Testing, etc just got a lot harder.

I think efforts could be better focused on functional areas and at least at this point, I don't see any data that shouldn't be public record (EG can't be stored in a git REPO).

**Comment by grekker** [comment]
Changed this to "database schema" since we decided to roll with a Salesforce org as the backing datastore. I've created a new repository https://github.com/open-force/website-org, and I'll be putting a DX project in there where we can build out the schema.

**Comment by grekker** [comment]
SF org created with simple schema.
